############################################################
# Dockerfile to build Nginx Installed Containers
# Based on Ubuntu
############################################################

FROM nginx:latest

# Copy nginx.conf file
COPY nginx.conf /etc/nginx/nginx.conf

# Make sites directories
RUN mkdir -p /etc/nginx/sites-available
RUN mkdir -p /etc/nginx/sites-enabled

# Copy a configuration file from the current directory
COPY proxy_params /etc/nginx/
COPY default /etc/nginx/sites-available/
COPY cache.conf /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/cache.conf /etc/nginx/sites-enabled/

# Expose ports
EXPOSE 80

# Set the default command to execute
# when creating a new container
CMD service nginx start