############################################################
# Dockerfile to build Nginx Installed Containers
# Based on Ubuntu
############################################################

FROM nginx:1.20-alpine

# Append "daemon off;" to the beginning of the configuration
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# Copy a configuration file from the current directory
ADD cache.conf /etc/nginx/sites-available
RUN ln -s /etc/nginx/sites-available/cache.conf /etc/nginx/sites-enabled

# Expose ports
EXPOSE 80

# Set the default command to execute
# when creating a new container
CMD service nginx start